//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Settings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6FsLGxuGeDI63dYUPflMwg==")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AD_turniket@pwr")]
        public string LDAPUserName {
            get {
                return ((string)(this["LDAPUserName"]));
            }
            set {
                this["LDAPUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uhh0joeX/12AzuPmHVrz5A==")]
        public string LDAPEncryptedPassword {
            get {
                return ((string)(this["LDAPEncryptedPassword"]));
            }
            set {
                this["LDAPEncryptedPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxDBConnectionCount {
            get {
                return ((int)(this["MaxDBConnectionCount"]));
            }
            set {
                this["MaxDBConnectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\nas\\media$\\ActivityManager\\ActivityManager.exe")]
        public string ActivityManagerPath {
            get {
                return ((string)(this["ActivityManagerPath"]));
            }
            set {
                this["ActivityManagerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cp866")]
        public string ActivityManagerOutputCodepage {
            get {
                return ((string)(this["ActivityManagerOutputCodepage"]));
            }
            set {
                this["ActivityManagerOutputCodepage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\nas\\media$\\ActivityManager\\templates\\registry")]
        public string ActivityManagerConfigsPath {
            get {
                return ((string)(this["ActivityManagerConfigsPath"]));
            }
            set {
                this["ActivityManagerConfigsPath"] = value;
            }
        }
    }
}
